version: '2'
services:
    gost-db:
        image: geodan/gost-db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: gost
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
    gost:
        image: geodan/gost
        ports:
            - "8080:8080"
        depends_on:
            - gost-db
        environment:
            GOST_SERVER_EXTERNAL_URI: http://gost:8080
            GOST_DB_HOST: gost-db